### ISSUE TITLE
cannot leave hostname entry on router blank

### ISSUE THREAD

**Issue by k1nghat** [ulygit/asus_rt_ac68u#1]
is this correct in your docs to leave it blank or should i input a hostname here? also i ran your `find / -name ddns-start.log 2>&1` command and it just returned new line. is that correct or should it have returned something?

**Comment by ulygit** [comment]
Hi k1nghat, I'm out of town so I can't look at my own config. I'm pretty sure my hostname entry was left blank. The hostname for the update is contained in the script itself. If your firmware requires it, you can probably put in anything and it will work fine. I think if you're configuring SSL the hostname may become a factor.

Regarding the 'find' command, you may be able to open the script and explicitly define the log file path. That way you don't have to search for it. I believe the advantage of the relative path to the log is that it is in a temporary path so you don't have to worry about the log growing to an enormous size. I don't think the file would actually grow very large anyway, but it's bad form not to consider the possibility.

I'll be back home Wednesday, so if you still have trouble let me know and I'll be happy to help then. You should include your firmware version since that child be a factor.

**Comment by k1nghat** [comment]
were you able to check if the hostname is blank on your end?

im also trying to have it get a LE cert but im not sure that its working? looking to set my VPN back up through the new hostname.

**Comment by ulygit** [comment]
Hello k1nghat, it turns out my host name is not blank, and the UI seems to require it. I have entered the correct host name in the UI, but I don't believe it's actually necessary unless you're configuring SSL.

I haven't tried configuring any cert, so I can't help you there. I'll update my docs to reflect that entering a host name is required (though I don't believe it's actually used).

Were you able to locate the log file?

**Comment by ulygit** [comment]
Happy to hear you got it working. I'll go ahead and close the ticket.
