### ISSUE TITLE
Feature Request - Update multiple DNS records

### ISSUE THREAD

**Issue by SBachman** [ulygit/asus_rt_ac68u#15]
I've got a unique need to update multiple records, one set to proxy and the other not proxied but both updated from the same router.

**Comment by ulygit** [comment]
That's a bit too unique a case to complicate the code base with, unfortunately. If this is a business need, please leave a contact email for follow-up.

**Comment by SBachman** [comment]
No, it's for a personal project. I figured as much but I thought it was worth asking. I'll just manually update one of them.

**Comment by LandazuriPaul** [comment]
@SBachman  Have you tried using CNAME records?

I would just avoid having a CNAME record for a top-level domain since it can conflict with other non A records (MX, TXT, etc.). But I reckon you could easily have a CNAME record for at least one subdomain of each of your top-level domains pointing at the subdomain you're currently updating with this repo's script and then handle local redirections between your different subdomains.

I hope my above explanation makes sense, but if you'd like some more in-depth details, don't hesitate. :)
