### ISSUE TITLE
Throttling/logging broken with 'date: invalid date '}''

### ISSUE THREAD

**Issue by bengalih** [ulygit/asus_rt_ac68u#8]
So again, I'm going to assume that CF API is returning data differently as we now get the following error on all runs after initial run where log file is created:

```
# ./cloudflare_ddns 6.6.6.7 
date: invalid date '}'
expr: syntax error
[: 1579631234: unknown operand
```

Issue appears to be from the following:

https://github.com/ulygit/asus_rt_ac68u/blob/116e522ea4dffdc63c2470ba795edaea32e3f22e/cloudflare_ddns#L84

When we sort and grep on the log file we get entries like the following:
```
s# sort -r cloudflare_ddns.log | grep -vm1 THROTTLED
}
```

Head of sorted log:
```
s# sort -r cloudflare_ddns.log | head -n7
}
}
}
}
2020-01-21 12:27        UPDATE_SUCCESS  {
2020-01-21 12:26        UPDATE_THROTTLED
2020-01-21 12:26        UPDATE_SUCCESS  {
```

So the operand is failing because it isn't matching a date on the "}" entries.
As I don't recall this being a problem before I can only assume that the return output from CF is now different and it appends this extra bracket on.

Seems like we can fix this by skipping those entries, like:

`last_run_time=$(date -d "$(sort -r $LOGFILE |  grep -v '}' | grep -vm1 THROTTLED | cut -f 1)" +%s) `

**Comment by ulygit** [comment]
I'll look to reproduce this tomorrow, as well. I did test updates, but I didn't look at repeated updates.

**Comment by ulygit** [comment]
I've thought over this, and I'm disinclined to incorporate your fix because of the possibility of making excessive calls to Cloudflare if the code enters an error state. Consider what happens if the script has a bug that produces a bad log entry when it's called. As it's coded now, the "bad" log entry will result in no call being made to CF. With your modification, the throttling will be effectively bypassed, and we'll be relying on the router firmware not to call too often.

The other problem is that checking specifically for the curly brace is too limiting. If you wanted to go this route, it's preferable to validate that the line begins with something that resembles a date via a regex match.

Regardless, rather than ignoring the bad entries, I'd like to have the code recognize there's a bad entry and fail explicitly with an explanation. That way the router is notified of the error (via the existing calls to /sbin/ddns_custom_updated), and the user will see a clear log message explaining that a throttle check failed because the script was unable to determine the elapsed time.

Let me know if you'd like to make this change. Otherwise, I'll get to it this weekend.

**Comment by bengalih** [comment]
We got out lines crossed a bit as I already realized a partial problem that I didn't want to filter out all lines with "}", but only lines beginning with them.  I edited my change to reflect this.

I admit I'm not following you however when you state that excessive calls will be made to CF.  As it stands, I believe my fix was simply addressing the unexpected data of '}".  It would appear based on your original code that you expect every line to being with a time/date stamp.  You performed a sort on this so that it was in numerical order and then filtered out all the THROTTLED entries to find the last time a non-throttled update occurred (whether or not it failed or not).  IOW, you would expect your sorted log to look something like this:

```
2020-01-21 12:37        UPDATE_FAILED  {
2020-01-21 12:27        UPDATE_SUCCESS  {
2020-01-21 12:26        UPDATE_THROTTLED
2020-01-21 12:16        UPDATE_SUCCESS  {
2020-01-21 12:09        UPDATE_SUCCESS  {
```

By capturing the top-most entry (that isn't a THROTTLED) we can deduce the last time the script was run and compare that last_run_time vs the throttled value to determine if we should run again or throttle.  Do I have that correct?

All I have done with my fix is remove the unexpected code of '}' that might appear in your sorted output causing a null value in last_run_time and thus the recorded error.

So, I'm not sure how I introduce a situation where we could cause excessive CF calls, if anything I have better protected against it.

Now, if what you are saying is that you would prefer not to simply weed out bad log entries one by one, but would rather validate a good date and if not then log that specifically and fail, then I understand.

However, if we plan to simply return an error and fail whenever an expected date is in the wrong format, wouldn't that prevent an update from ever occurring if the log file is not what we expect?

It would seem to me that perhaps the best method may be to:
`grep -v 'UPDATE_' | grep -vm1 'THROTTLED'`

This way we are sure to only pull out the lines with an expected format.

?

**Comment by ulygit** [comment]
I took a look at the CF API docs, and it appears they rate-limit to 1500 calls per 5 minute period. That's a pretty generous limit, so I'm less concerned about excessive calls. My worry was that we could be making repeated calls to CF that produce broken log entries, but we would ignore those entries and continue making calls.

I'm ok with making the sort of change you suggest, but let's instead search for a valid date format. I'm going to implement something like below.

`grep '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}' ...`

That way we know we're getting something very date-like.

**Comment by ulygit** [comment]
Issue has been fixed.
